/**
 * AuthorizationPort.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.2.1 Jun 14, 2005 (09:15:57 EDT) WSDL2Java emitter.
 */

package com.bea.security.ssmws.service;

public interface AuthorizationPort extends java.rmi.Remote {
    public com.bea.security.ssmws.types.ServiceVersionType getVersion() throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType;
    public com.bea.security.ssmws.types.ServiceCompatibilityEnum isCompatible(com.bea.security.ssmws.types.ServiceVersionType serviceVersion) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType;
    public void queryActionsOnResource(com.bea.security.ssmws.types.IdentityAssertionType identityAssertion, com.bea.security.ssmws.types.RuntimeResourceType runtimeResource, com.bea.security.ssmws.types.RequestedActionsType requestedActions, com.bea.security.ssmws.types.ContextType appContext, com.bea.security.ssmws.types.holders.RuntimeEntitlementTypeHolder runtimeEntitlement, com.bea.security.ssmws.types.holders.ContextTypeHolder responseContext) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public void establishSession(com.bea.security.ssmws.types.PrincipalsInfoType principalsInfo, java.lang.String requestedCredentialType, com.bea.security.ssmws.types.ContextType appContext, com.bea.security.ssmws.types.holders.IdentityAssertionTypeHolder identityAssertion, com.bea.security.ssmws.types.holders.ChallengeTypeHolder challenge, org.w3.www._2001.XMLSchema.holders.StringArrayHolder statusInfo) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public com.bea.security.ssmws.types.ExtendedAuthorizationResultType[] isChildResourceAccessAllowed(com.bea.security.ssmws.types.IdentityAssertionType identityAssertion, com.bea.security.ssmws.types.ResourceActionType resourceAction, java.lang.String requestedCredentialType, com.bea.security.ssmws.types.ContextType appContext) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public com.bea.security.ssmws.types.ExtendedAuthorizationResultType[] isBulkAccessAllowed(com.bea.security.ssmws.types.IdentityAssertionType identityAssertion, com.bea.security.ssmws.types.ResourceActionType[] resourceAction, java.lang.String requestedCredentialType, com.bea.security.ssmws.types.ContextType appContext) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public void isAccessAllowed(com.bea.security.ssmws.types.IdentityAssertionType identityAssertion, com.bea.security.ssmws.types.RuntimeResourceType runtimeResource, com.bea.security.ssmws.types.RuntimeActionType runtimeAction, java.lang.String requestedCredentialType, com.bea.security.ssmws.types.ContextType appContext, com.bea.security.ssmws.types.AtzDirectionEnum atzDirection, javax.xml.rpc.holders.BooleanHolder accessAllowed, com.bea.security.ssmws.types.holders.AtzDecisionDataTypeHolder atzDecisionData, com.bea.security.ssmws.types.holders.ContextRequestsTypeHolder contextRequests) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public com.bea.security.ssmws.types.ServiceTypeEnum getServiceType() throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType;
    public void queryActionsOnChildResource(com.bea.security.ssmws.types.IdentityAssertionType identityAssertion, com.bea.security.ssmws.types.RuntimeResourceType runtimeResource, com.bea.security.ssmws.types.RequestedActionsType requestedActions, com.bea.security.ssmws.types.ContextType appContext, com.bea.security.ssmws.types.holders.RuntimeEntitlementTypeArrayHolder entitlementList, com.bea.security.ssmws.types.holders.ContextTypeHolder responseContext) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public boolean isAuthenticationRequired(com.bea.security.ssmws.types.RuntimeResourceType runtimeResource, com.bea.security.ssmws.types.RuntimeActionType runtimeAction) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
    public void isAccessAllowedDebug(com.bea.security.ssmws.types.IdentityAssertionType identityAssertion, com.bea.security.ssmws.types.RuntimeResourceType runtimeResource, com.bea.security.ssmws.types.RuntimeActionType runtimeAction, java.lang.String requestedCredentialType, com.bea.security.ssmws.types.ContextType appContext, javax.xml.rpc.holders.BooleanHolder accessAllowed, com.bea.security.ssmws.types.holders.AtzDecisionDataTypeHolder atzDecisionData, com.bea.security.ssmws.types.holders.ContextRequestsTypeHolder contextRequests, com.bea.security.ssmws.types.holders.DebugInfoTypeHolder debugInfo) throws java.rmi.RemoteException, com.bea.security.ssmws.types.FaultInfoType, com.bea.security.ssmws.types.FaultInfoType;
}
