package com.trilliumsoftware.director.j2ee.ejb;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Aug 11 15:24:20 CDT 2011  
 */

public interface DirectorWebService extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: DirectorWebServicePort  
     // Port Type: DirectorWebServicePort   
     //***********************************
     
  /**
   * returns DirectorWebServicePort port in this service 
   */
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getDirectorWebServicePort(byte[] username, byte[] password);
   */
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(String username, String password) throws javax.xml.rpc.ServiceException;

  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }