package com.trilliumsoftware.director.j2ee.ejb;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Aug 11 15:24:20 CDT 2011 */

public class DirectorWebService_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements com.trilliumsoftware.director.j2ee.ejb.DirectorWebService {

  public DirectorWebService_Impl() throws javax.xml.rpc.ServiceException {
    this("com/trilliumsoftware/director/j2ee/ejb/DirectorWebService_saved_wsdl.wsdl", null);
  }
  
  public DirectorWebService_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public DirectorWebService_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://ejb.j2ee.director.trilliumsoftware.com", "DirectorWebService"),
          "com/trilliumsoftware/director/j2ee/ejb/DirectorWebService_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: DirectorWebServicePort 
  // Port Type: DirectorWebServicePort 
  //***********************************

  com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort mvar_DirectorWebServicePort;

  /**
   * returns DirectorWebServicePort port in this service 
   */
  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_DirectorWebServicePort == null) {
      mvar_DirectorWebServicePort =
        new com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort_Stub(_getPort("DirectorWebServicePort"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_DirectorWebServicePort)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_DirectorWebServicePort;
  }

  /**
   * @deprecated  Use getDirectorWebServicePort(byte[] username, byte[] password)
   */
  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getDirectorWebServicePort();
  }

  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getDirectorWebServicePort();
  }
  
      public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("DirectorWebServicePort", policyInputStream, true, true);
    return getDirectorWebServicePort();
  }

  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("DirectorWebServicePort", policyInputStream, inbound, outbound);
    return getDirectorWebServicePort();
  }
 
  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("DirectorWebServicePort", null, inboundPolicies, outboundPolicies);
    return getDirectorWebServicePort();
  }
  
  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("DirectorWebServicePort", null, inboundPolicies, outboundPolicies);
    return getDirectorWebServicePort();
  }
  
  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("DirectorWebServicePort", operationName, inboundPolicies, outboundPolicies);
    return getDirectorWebServicePort();
  }
  
  public com.trilliumsoftware.director.j2ee.ejb.DirectorWebServicePort getDirectorWebServicePort(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("DirectorWebServicePort", operationName, inboundPolicies, outboundPolicies);
    return getDirectorWebServicePort();
  }
    
}