package org.cap.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 09 14:56:01 CST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpAppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl)findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl)findViewObject("CountriesView1");
    }

    /**
     * Container's getter for LocationsView1.
     * @return LocationsView1
     */
    public ViewObjectImpl getLocationsView1() {
        return (ViewObjectImpl)findViewObject("LocationsView1");
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl)findViewObject("RegionsView1");
    }

    /**
     * Container's getter for CountriesView1_1.
     * @return CountriesView1_1
     */
    public ViewObjectImpl getCountriesView1_1() {
        return (ViewObjectImpl)findViewObject("CountriesView1_1");
    }

    /**
     * Container's getter for LocationsView1_1.
     * @return LocationsView1_1
     */
    public ViewObjectImpl getLocationsView1_1() {
        return (ViewObjectImpl)findViewObject("LocationsView1_1");
    }

    /**
     * Container's getter for RegionsView1_1.
     * @return RegionsView1_1
     */
    public ViewObjectImpl getRegionsView1_1() {
        return (ViewObjectImpl)findViewObject("RegionsView1_1");
    }

    /**
     * Container's getter for LocationsView2.
     * @return LocationsView2
     */
    public ViewObjectImpl getLocationsView2() {
        return (ViewObjectImpl)findViewObject("LocationsView2");
    }

    /**
     * Container's getter for CountriesView2.
     * @return CountriesView2
     */
    public ViewObjectImpl getCountriesView2() {
        return (ViewObjectImpl)findViewObject("CountriesView2");
    }

    /**
     * Container's getter for LocationsView1_2.
     * @return LocationsView1_2
     */
    public ViewObjectImpl getLocationsView1_2() {
        return (ViewObjectImpl)findViewObject("LocationsView1_2");
    }

    /**
     * Container's getter for CountriesView1_2.
     * @return CountriesView1_2
     */
    public ViewObjectImpl getCountriesView1_2() {
        return (ViewObjectImpl)findViewObject("CountriesView1_2");
    }

    /**
     * Container's getter for LocCIdFkLink1.
     * @return LocCIdFkLink1
     */
    public ViewLinkImpl getLocCIdFkLink1() {
        return (ViewLinkImpl)findViewLink("LocCIdFkLink1");
    }

    /**
     * Container's getter for CountrRegFkLink1.
     * @return CountrRegFkLink1
     */
    public ViewLinkImpl getCountrRegFkLink1() {
        return (ViewLinkImpl)findViewLink("CountrRegFkLink1");
    }

    /**
     * Container's getter for LocCIdFkLink1_1.
     * @return LocCIdFkLink1_1
     */
    public ViewLinkImpl getLocCIdFkLink1_1() {
        return (ViewLinkImpl)findViewLink("LocCIdFkLink1_1");
    }

    /**
     * Container's getter for CountrRegFkLink1_1.
     * @return CountrRegFkLink1_1
     */
    public ViewLinkImpl getCountrRegFkLink1_1() {
        return (ViewLinkImpl)findViewLink("CountrRegFkLink1_1");
    }
}
