package com.trilliumsoftware.director.j2ee.ejb;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Aug 11 15:24:20 CDT 2011  
 */

public interface DirectorWebServicePort extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}setTraceFile   */

  public void setTraceFile(java.lang.String string) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void setTraceFileAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String string) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}setTraceOff   */

  public void setTraceOff() throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void setTraceOffAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}setTraceOn   */

  public void setTraceOn() throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void setTraceOnAsync(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}cleanse   */

  public com.trilliumsoftware.director.j2ee.transfer.CleanseResults cleanse(com.trilliumsoftware.director.j2ee.transfer.CleanserInput cleanserInput) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void cleanseAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.trilliumsoftware.director.j2ee.transfer.CleanserInput cleanserInput) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}matchCandidate   */

  public com.trilliumsoftware.director.j2ee.transfer.MatchResults matchCandidate(com.trilliumsoftware.director.j2ee.transfer.MatchCandidateInput matchCandidateInput) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void matchCandidateAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.trilliumsoftware.director.j2ee.transfer.MatchCandidateInput matchCandidateInput) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}matchCandidateWithSuspects   */

  public com.trilliumsoftware.director.j2ee.transfer.MatchResults matchCandidateWithSuspects(com.trilliumsoftware.director.j2ee.transfer.MatchCandidateWithSuspectsInput matchCandidateWithSuspectsInput) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void matchCandidateWithSuspectsAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.trilliumsoftware.director.j2ee.transfer.MatchCandidateWithSuspectsInput matchCandidateWithSuspectsInput) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}cleanseXML   */

  public java.lang.String cleanseXML(com.trilliumsoftware.director.j2ee.transfer.CleanserXMLInput cleanserXMLInput) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void cleanseXMLAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.trilliumsoftware.director.j2ee.transfer.CleanserXMLInput cleanserXMLInput) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}matchCandidateWithSuspectsXML   */

  public java.lang.String matchCandidateWithSuspectsXML(com.trilliumsoftware.director.j2ee.transfer.MatcherCandidateSuspectsXMLInput matcherCandidateSuspectsXMLInput) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void matchCandidateWithSuspectsXMLAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.trilliumsoftware.director.j2ee.transfer.MatcherCandidateSuspectsXMLInput matcherCandidateSuspectsXMLInput) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}matchCandidateXML   */

  public java.lang.String matchCandidateXML(com.trilliumsoftware.director.j2ee.transfer.MatcherXMLInput matcherXMLInput) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void matchCandidateXMLAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.trilliumsoftware.director.j2ee.transfer.MatcherXMLInput matcherXMLInput) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}setTraceFile0   */

  public void setTraceFile0(java.lang.String string) throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void setTraceFile0Async(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String string) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}setTraceOff0   */

  public void setTraceOff0() throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void setTraceOff0Async(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://ejb.j2ee.director.trilliumsoftware.com}setTraceOn0   */

  public void setTraceOn0() throws java.rmi.RemoteException, com.trilliumsoftware.director.j2ee.transfer.DirectorServiceException;
    public void setTraceOn0Async(weblogic.wsee.async.AsyncPreCallContext apc ) throws java.rmi.RemoteException ;
  
}